### PR TITLE
Fix underflow and out of bounds errors

### LINKED ISSUE #3: Underflow when the first line expires
Hello again,

it looks like if the first line in the list of lines reaches it's duration limit and expires, then an underflow occurs.

The underflow occurs here: https://github.com/Toqozz/bevy_debug_lines/blob/8f7d2eb7603d32211ef372bc33084a7f89f86010/src/lib.rs#L277

Here is a small reproduction:

```rust
use bevy::prelude::*;
use bevy_prototype_debug_lines::*;

fn main() {
    App::build()
        .insert_resource(Msaa { samples: 4 })
        .add_plugins(DefaultPlugins)
        .add_plugin(DebugLinesPlugin)
        .add_startup_system(setup.system())
        .add_system(demo.system())
        .run();
}

fn setup(mut commands: Commands) {
    let mut camera = OrthographicCameraBundle::new_2d();
    camera.transform = Transform::from_translation(Vec3::new(0.0, 0.0, 5.0));
    commands.spawn_bundle(camera);
}

#[derive(Default)]
struct Counter {
    count: i32,
}

fn demo(mut counter: Local<Counter>, mut lines: ResMut<DebugLines>) {
    if counter.count == 0 {
        // This line is the first to be added, when it expires it will cause a panic
        lines.line(Vec3::new(-400.0, 200.0, 0.0), Vec3::new(400.0, 200.0, 0.0), 0.0);
    }
    lines.line(Vec3::new(-400.0, -200.0, 0.0), Vec3::new(400.0, -200.0, 0.0), 10.0);
    counter.count += 1;
}
```

### PR DESCRIPTION
**Pull request by atbentley**
While fixing the underflow bug I also found that sometimes an out of bound error also occurs. I've included a fix for that too but I'm not 100% if this fix is correct as I don't have a small reproduction for it. I believe this out of bounds error occurs when there all remaining lines are removed in a single frame, bring the line count down to zero.

Fixes #3

### CODE REVIEW

**Comment by Toqozz** [comment]
Ahh, that underflow seems amateur.  I think this happens because `i` is intended to go below 0, but I didn't think about `usize` limitations.

```rust
let mut i = 0;
let mut len = lines.lines.len();    // len == 1;
while i != len {
    lines.lines[i].duration -= time.delta_seconds();
    if lines.lines[i].duration < 0.0 {
        lines.lines.swap(i, len - 1);    // swap with itself, 
        len -= 1;    // len == 0
        i -= 1;    // i == -1
    }

    i += 1;    // i == 0, everything is ok.
}
```

I think a more elegant approach may be to avoid subtracting from `i` entirely and just have `i += 1` in an `else` block.

File: src/lib.rs [hunk 1]
```diff
@@ -269,12 +269,12 @@ fn draw_lines(
 
     let mut i = 0;
     let mut len = lines.lines.len();
-    while i != len {
+    while i < len {
```
Comment (Toqozz) [inline src/lib.rs:272]:
```suggestion
    while i != len {
```

File: src/lib.rs [hunk 2]
```diff
@@ -269,12 +269,12 @@ fn draw_lines(
...
         lines.lines[i].duration -= time.delta_seconds();
         if lines.lines[i].duration < 0.0 {
             lines.lines.swap(i, len - 1);
             len -= 1;
-            i -= 1;
+            i = i.saturating_sub(1);
         }
 
         i += 1;
```
Comment (Toqozz) [inline src/lib.rs:280]:
```suggestion
        } else {
            i += 1;
        }
```

**Review by Toqozz — CHANGES_REQUESTED** [review]
GitHub made that kind of annoying to suggest, here it is in full:
```rust
    let mut i = 0;
    let mut len = lines.lines.len();
    while i != len {
        lines.lines[i].duration -= time.delta_seconds();
        if lines.lines[i].duration < 0.0 {
            lines.lines.swap(i, len - 1);
            len -= 1;
        } else {
            i += 1;
        }
    }
```

I'd like to keep the `i != len` because I'd prefer to panic than fail silently.
